parameters:
    kernel_class: 'Rector\Symfony\Tests\Symfony42\Rector\MethodCall\AbstractToConstructorInjectionRectorSource\SomeKernelClass'

services:
    Rector\Symfony4\Rector\FrameworkBundle\ContainerGetToConstructorInjectionRector:
        $containerAwareParentTypes:
            - 'Rector\Symfony\Tests\Symfony42\Rector\MethodCall\ContainerGetToConstructorInjectionRector\Source\ContainerAwareParentClass'
